### ISSUE TITLE
"click here" links work in Firefox, not Chrome

### ISSUE THREAD

**Issue by kayakr** [catalyst-cloud/catalystcloud-docs#251]
https://docs.catalystcloud.io/identity-access-management/roles.html has multiple "click here" links that expose additional data.
These don't work for me at all in Chrome Version 83.0.4103.116 (Official Build) (64-bit) on MacOS.
They do work for me in Firefox.
IMO, they should be removed as "click here" is not useful for accessibility; just show the tables in line.

**Comment by chelios** [comment]
Thanks for the feedback. 

The functionality does seem to be inconsistent. 

Chrome : you get the triangle indicating collapsed content and the click here link. The triangle works but the link does not.
Safair : you get the triangle indicating collapsed content and the click here link. The triangle and the link work. 
Firefox: click here link only. Link works.

The reason for trying to collapse the content is that a couple of the tables are quite long, in the case of the member role it is almost 200 lines by itself. This means that the trade off is then lots of scrolling in order to view the content. We will investigate and see what alternatives we can come up with.

**Comment by puck** [comment]
Perhaps for the large tables have them in an appendix?

I'd also note that "click here" really grates on me. Only makes sense if people are using a mouse.
